name: Update AWS Lambda Images

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Java11 Branch from AWS Lambda Base Images Repository
        run: |
          git clone --branch java11 --depth 1 "https://github.com/aws/aws-lambda-base-images.git" aws-lambda-java11
          echo "Listing contents of AWS Lambda Java11 directory..."
          ls -alh aws-lambda-java11/x86_64/

      - name: Clone Python3.10 Branch from AWS Lambda Base Images Repository
        run: |
          git clone --branch python3.10 --depth 1 "https://github.com/aws/aws-lambda-base-images.git" aws-lambda-python3.10
          echo "Listing contents of AWS Lambda Python3.10 directory..."
          ls -alh aws-lambda-python3.10/x86_64/

      - name: Clone Docker Library Repository
        run: |
          git clone --branch main "https://github.com/thisis-charan/dockerlibtest1.git" dockerlibrary

      - name: Sync Images and Commit Changes
        run: |
          function sync_lambda_images() {
            local aws_repo_dir=$1
            local docker_repo_dir=$2
            local update_required=false
            declare -A aws_files_hash
            declare -A docker_files_hash

            if [ ! -d "$aws_repo_dir" ] || [ -z "$(ls -A $aws_repo_dir/*.tar.xz 2>/dev/null)" ]; then
              echo "No files found in $aws_repo_dir. Continuing with other directories..."
              return
            else
              echo "Files found in $aws_repo_dir:"
              ls $aws_repo_dir/*.tar.xz
            fi

            if [ ! -d "$docker_repo_dir" ]; then
              echo "Creating Docker directory $docker_repo_dir..."
              mkdir -p "$docker_repo_dir"
            fi

            for file in $aws_repo_dir/*.tar.xz; do
              if [ -f "$file" ]; then
                hash=$(sha256sum "$file" | awk '{print $1}')
                aws_files_hash["$hash"]=$(basename "$file")
              fi
            done

            for file in $docker_repo_dir/*.tar.xz; do
              if [ -f "$file" ]; then
                hash=$(sha256sum "$file" | awk '{print $1}')
                docker_files_hash["$hash"]=$(basename "$file")
              fi
            done

            for hash in "${!aws_files_hash[@]}"; do
              if [[ ! ${docker_files_hash["$hash"]+_} ]]; then
                update_required=true
                echo "Differences detected, updating..."
                rm -f $docker_repo_dir/*.tar.xz
                for file in "${aws_files_hash[@]}"; do
                  cp "$aws_repo_dir/$file" "$docker_repo_dir/"
                done
              fi
            done

            if [ "$update_required" == false ]; then
              echo "No differences found, no update required."
            fi
          }

          sync_lambda_images "aws-lambda-java11/x86_64" "dockerlibrary/lambda/java/11"
          sync_lambda_images "aws-lambda-python3.10/x86_64" "dockerlibrary/lambda/python/3.10"

          cd dockerlibrary
          if git status --porcelain; then
            git add .
            git commit -m "Updated AWS Lambda base images"
            git push
          else
            echo "No changes to commit"
        shell: bash
