name: single matrix

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - aws_branch: 'java11'
            local_dir: 'lambda/java/11'
          - aws_branch: 'python3.10'
            local_dir: 'lambda/python/3.10'
          # Add more configurations as needed

    steps:
      - name: Clone AWS Lambda Base Image Repository
        run: |
          git clone --branch ${{ matrix.aws_branch }} --depth 1 "https://github.com/aws/aws-lambda-base-images.git" aws-lambda-${{ matrix.aws_branch }}
          echo "Cloned ${{ matrix.aws_branch }} branch successfully"

      - name: Clone Docker Library
        run: |
          git clone "https://github.com/thisis-charan/dockerlibtest1.git" dockerlibrary
          echo "Cloned Docker library successfully"

      - name: Sync Images
        run: |
          aws_repo_dir="aws-lambda-${{ matrix.aws_branch }}/x86_64"
          docker_repo_dir="dockerlibrary/${{ matrix.local_dir }}"
          echo "Starting sync for $aws_repo_dir to $docker_repo_dir"
          
          mkdir -p "$docker_repo_dir"
          rm -f $docker_repo_dir/*.tar.xz
          
          cp $aws_repo_dir/*.tar.xz $docker_repo_dir/
          echo "Copied new .tar.xz files to $docker_repo_dir"

      - name: Create and push new branch
        id: create_branch
        run: |
          cd dockerlibrary
          new_branch="feature/$(date +'%Y%m%d-%H%M%S')"
          git checkout -b "$new_branch"
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add .
          git commit -m "Updated AWS Lambda base images"
          git push --set-upstream origin "$new_branch"
          echo "::set-output name=branch_name::$new_branch"

      - name: Create Pull Request
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.MY_GITHUB_PAT }}
          script: |
            const title = "Update AWS Lambda base images";
            const body = "This PR updates the AWS Lambda base images to the latest versions across multiple environments.";
            const head = "${{ steps.create_branch.outputs.branch_name }}";
            const base = 'main';
            const draft = false;
            github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              head: head,
              base: base,
              draft: draft,
            });

