jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clone AWS Lambda Base Images Repository
        run: |
          git clone --depth 1 "https://github.com/aws/aws-lambda-base-images.git" aws-lambda

      - name: Clone Docker Library Repository
        run: |
          git clone --branch main "https://github.com/thisis-charan/dockerlibtest1.git" dockerlibrary

      - name: Sync Images and Commit Changes
        run: |
          function sync_lambda_images() {
            local aws_repo_dir=$1
            local docker_repo_dir=$2
            local update_required=false
            declare -A aws_files_hash
            declare -A docker_files_hash
            
            # Calculate hashes for AWS files
            for file in $aws_repo_dir/*.tar.xz; do
              hash=$(sha256sum "$file" | awk '{print $1}')
              aws_files_hash["$hash"]=$(basename "$file")
            done

            # Calculate hashes for Docker files
            for file in $docker_repo_dir/*.tar.xz; do
              hash=$(sha256sum "$file" | awk '{print $1}')
              docker_files_hash["$hash"]=$(basename "$file")
            done

            # Check for differences and update if necessary
            for hash in "${!aws_files_hash[@]}"; do
              if [[ ! ${docker_files_hash["$hash"]+_} ]]; then
                update_required=true
                echo "Differences detected, updating..."
                rm -f $docker_repo_dir/*.tar.xz
                for file in "${aws_files_hash[@]}"; do
                  cp "$aws_repo_dir/$file" "$docker_repo_dir/"
                done
              fi
            done

            if [ "$update_required" = false ]; then
              echo "No differences found, no update required."
            fi
          }

          # Call the function for Java
          sync_lambda_images "aws-lambda/java11/x86_64" "dockerlibrary/lambda/java/11"

          # Call the function for Python
          sync_lambda_images "aws-lambda/python3.10/x86_64" "dockerlibrary/lambda/python/3.10"

          # Commit and push if changes were made
          cd dockerlibrary
          if git status --porcelain; then
            git add .
            git commit -m "Updated AWS Lambda base images"
            git push
          else
            echo "No changes to commit"
        shell: bash
