name: Update AWS Lambda Images

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repositories
        run: |
          # Cloning AWS Lambda Base Images Repository
          git clone "https://github.com/aws/aws-lambda-base-images.git" aws-lambda
          # Cloning Docker Library Repository
          git clone --branch main "https://github.com/thisis-charan/dockerlibtest1.git" dockerlibrary

      - name: Sync Images and Commit Changes
        run: |
          # Define sync function within the same script block
          function sync_lambda_images() {
            local aws_repo_dir=$1
            local docker_repo_dir=$2
            local update_required=false
            declare -A aws_files_hash
            declare -A docker_files_hash

            echo "Checking files in AWS repo directory: $aws_repo_dir"
            if [ ! -d "$aws_repo_dir" ] || [ -z "$(ls -A $aws_repo_dir/*.tar.xz 2>/dev/null)" ]; then
              echo "No files found in $aws_repo_dir. Continuing with other directories..."
              return  # Graceful exit if no files are found
            fi

            echo "Checking files in Docker repo directory: $docker_repo_dir"
            if [ ! -d "$docker_repo_dir" ]; then
              echo "Docker directory $docker_repo_dir not found, creating it..."
              mkdir -p "$docker_repo_dir"
            fi

            # Calculate hashes for AWS files
            for file in $aws_repo_dir/*.tar.xz; do
              if [ -f "$file" ]; then
                hash=$(sha256sum "$file" | awk '{print $1}')
                aws_files_hash["$hash"]=$(basename "$file")
              fi
            done

            # Calculate hashes for Docker files
            for file in $docker_repo_dir/*.tar.xz; do
              if [ -f "$file" ]; then
                hash=$(sha256sum "$file" | awk '{print $1}')
                docker_files_hash["$hash"]=$(basename "$file")
              fi
            done

            # Check for differences and update if necessary
            for hash in "${!aws_files_hash[@]}"; do
              if [[ ! ${docker_files_hash["$hash"]+_} ]]; then
                update_required=true
                echo "Differences detected, updating..."
                rm -f $docker_repo_dir/*.tar.xz
                for file in "${aws_files_hash[@]}"; do
                  cp "$aws_repo_dir/$file" "$docker_repo_dir/"
                done
              fi
            done

            if [ "$update_required" == false ]; then
              echo "No differences found, no update required."
            fi
          }

          # Call the function for Java
          sync_lambda_images "aws-lambda/java11/x86_64" "dockerlibrary/lambda/java/11"

          # Call the function for Python
          sync_lambda_images "aws-lambda/python3.10/x86_64" "dockerlibrary/lambda/python/3.10"

          # Commit and push if changes were made
          cd dockerlibrary
          if git status --porcelain; then
            git add .
            git commit -m "Updated AWS Lambda base images"
            git push
          else
            echo "No changes to commit"
        shell: bash
