name: Update AWS Lambda Images

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clone AWS Lambda Base Images Repository
        run: |
          git clone --depth 1 "https://github.com/aws/aws-lambda-base-images.git" aws-lambda

      - name: Clone Docker Library Repository
        run: |
          git clone --branch main "https://github.com/thisis-charan/dockerlibtest1.git" dockerlibrary

      - name: Sync Java 11 AWS Lambda Images to Docker Library
        run: |
          aws_repo_dir="aws-lambda/java11/x86_64"
          docker_repo_dir="dockerlibrary/lambda/java/11"
          sync_lambda_images "$aws_repo_dir" "$docker_repo_dir"

      - name: Sync Python 3.10 AWS Lambda Images to Docker Library
        run: |
          aws_repo_dir="aws-lambda/python3.10/x86_64"
          docker_repo_dir="dockerlibrary/lambda/python/3.10"
          sync_lambda_images "$aws_repo_dir" "$docker_repo_dir"

      - name: Commit and Push Updates if Needed
        run: |
          cd dockerlibrary
          if git status --porcelain; then
            git add .
            git commit -m "Updated AWS Lambda base images"
            git push
          else
            echo "No changes to commit"

      - name: Cleanup
        run: |
          rm -rf aws-lambda
          rm -rf dockerlibrary

# Helper function to avoid code duplication
      - name: Define sync function
        run: |
          echo 'sync_lambda_images() {
            aws_repo_dir=$1
            docker_repo_dir=$2
            update_required=false
        
            declare -A aws_files_hash
            declare -A docker_files_hash
        
            for file in $aws_repo_dir/*.tar.xz; do
              hash=$(sha256sum "$file" | awk "{print $1}")
              aws_files_hash["$hash"]=$(basename "$file")
            done
        
            for file in $docker_repo_dir/*.tar.xz; do
              hash=$(sha256sum "$file" | awk "{print $1}")
              docker_files_hash["$hash"]=$(basename "$file")
            done
        
            for hash in "${!aws_files_hash[@]}"; do
              if [[ ! ${docker_files_hash["$hash"]+_} ]]; then
                update_required=true
                echo "Differences detected, updating..."
                rm -f $docker_repo_dir/*.tar.xz
                for file in "${aws_files_hash[@]}"; do
                  cp "$aws_repo_dir/$file" "$docker_repo_dir/"
                done
              fi
            done
        
            if [ "$update_required" = false ]; then
              echo "No differences found, no update required."
            fi
          }' >> $HOME/.bashrc
        shell: bash
