name: Update AWS Lambda Images

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Specific Branches
        run: |
          git clone --branch java11 --depth 1 "https://github.com/aws/aws-lambda-base-images.git" aws-lambda-java11
          git clone --branch python3.10 --depth 1 "https://github.com/aws/aws-lambda-base-images.git" aws-lambda-python3.10
          git clone --branch main "https://github.com/thisis-charan/dockerlibtest1.git" dockerlibrary

      - name: Sync Images and Commit Changes
        run: |
          function sync_lambda_images() {
            local aws_repo_dir=$1
            local docker_repo_dir=$2
            local update_required=false
            declare -A aws_files_hash
            declare -A docker_files_hash

            echo "Checking files in AWS repo directory: $aws_repo_dir"
            if [ ! -d "$aws_repo_dir" ]; then
              echo "AWS directory $aws_repo_dir not found."
              return
            elif [ -z "$(ls -A $aws_repo_dir/*.tar.xz 2>/dev/null)" ]; then
              echo "No .tar.xz files found in $aws_repo_dir."
              return
            fi

            if [ ! -d "$docker_repo_dir" ]; then
              echo "Creating Docker directory $docker_repo_dir..."
              mkdir -p "$docker_repo_dir"
            fi

            for file in $aws_repo_dir/*.tar.xz; do
              if [ -f "$file" ]; then
                local hash=$(sha256sum "$file" | awk '{print $1}')
                aws_files_hash["$hash"]=$(basename "$file")
              fi
            done

            for file in $docker_repo_dir/*.tar.xz; do
              if [ -f "$file" ]; then
                local hash=$(sha256sum "$file" | awk '{print $1}')
                docker_files_hash["$hash"]=$(basename "$file")
              fi
            done

            for hash in "${!aws_files_hash[@]}"; do
              if [[ ! ${docker_files_hash["$hash"]+_} ]]; then
                update_required=true
                echo "Differences detected, updating..."
                rm -f "$docker_repo_dir"/*.tar.xz
                cp "$aws_repo_dir"/*.tar.xz "$docker_repo_dir/"
              fi
            done

            if [ "$update_required" == false ]; then
              echo "No differences found, no update required."
            fi
          }

          # Sync files for Java and Python
          sync_lambda_images "aws-lambda-java11/x86_64" "dockerlibrary/lambda/java/11"
          sync_lambda_images "aws-lambda-python3.10/x86_64" "dockerlibrary/lambda/python/3.10"

          # Commit and push changes if there are any
          cd dockerlibrary
          if git status --porcelain; then
            git add .
            git commit -m "Updated AWS Lambda base images"
            git push
          else
            echo "No changes to commit"
        shell: bash
