name: SNS Email Notification

# Trigger manually and pass an email address as input.
on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Email address to send notification'
        required: true
        default: 'example@example.com'

jobs:
  send-notification:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # Required for OIDC-based AWS credentials
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::390844772055:role/SnsEmailNotifyTest
          aws-region: us-east-1

      # Optional: Subscribe the provided email to the SNS topic.
      # If the email is not yet subscribed (or pending confirmation), this call will
      # trigger a confirmation email to the recipient.
      - name: Subscribe Email to SNS Topic (Optional)
        run: |
          echo "Subscribing ${{ github.event.inputs.email }} to SNS topic..."
          aws sns subscribe \
            --topic-arn arn:aws:sns:us-east-1:390844772055:EmailNotifyTest \
            --protocol email \
            --notification-endpoint "${{ github.event.inputs.email }}"

      # Set the filter policy for the subscription corresponding to the input email.
      - name: Set SNS Subscription Filter Policy
        run: |
          echo "Looking up subscription ARN for email: ${{ github.event.inputs.email }}"
          # List all subscriptions for the topic and filter for the one with the matching email.
          SUBSCRIPTION_ARN=$(aws sns list-subscriptions-by-topic \
            --topic-arn arn:aws:sns:us-east-1:390844772055:EmailNotifyTest \
            | jq -r '.Subscriptions[] | select(.Endpoint=="'"${{ github.event.inputs.email }}"'") | .SubscriptionArn')
          
          echo "Found subscription ARN: $SUBSCRIPTION_ARN"
          if [ -z "$SUBSCRIPTION_ARN" ]; then
            echo "Subscription for ${{ github.event.inputs.email }} not found. Please ensure that the email is subscribed and confirmed."
            exit 1
          fi
          
          echo "Setting filter policy for the subscription..."
          aws sns set-subscription-attributes \
            --subscription-arn "$SUBSCRIPTION_ARN" \
            --attribute-name FilterPolicy \
            --attribute-value '{"targetEmail": ["'"${{ github.event.inputs.email }}"'"]}'


      - name: Publish Notification Message to SNS Topic
        run: |
          echo "Publishing message to SNS topic..."
          aws sns publish \
            --topic-arn arn:aws:sns:us-east-1:390844772055:EmailNotifyTest \
            --subject "GitHub Actions Notification" \
            --message "This is a notification from GitHub Actions." \
            --message-attributes '{"targetEmail": {"DataType": "String", "StringValue": "'"${{ github.event.inputs.email }}"'"}}'
