name: Sync Python 3.10 Folder with Repo2

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo1
        uses: actions/checkout@v2
        with:
          path: 'repo1'

      - name: Checkout Repo2
        uses: actions/checkout@v2
        with:
          repository: 'thisis-charan/dockerlibtest2'
          path: 'repo2'

      - name: Sync Python 3.10 Folder
        env:
          MY_GITHUB_PAT: ${{ secrets.MY_GITHUB_PAT }}
        run: |
          rsync -a --delete repo2/python/3.10/ repo1/python/3.10/

      - name: Commit and Push Changes to Repo1
        env:
          MY_GITHUB_PAT: ${{ secrets.MY_GITHUB_PAT }}
        run: |
          cd repo1
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add python/3.10
          git commit -m "Sync python3.10 folder with dockerlibtest2" || echo "No changes to commit"
          git push --set-upstream https://${{ secrets.MY_GITHUB_PAT }}@github.com/thisis-charan/dockerlibtest1.git main
